gpio inputs in DT
twonav/linux-2.6-imx pull request #106
Opened 2022-07-01 12:34 UTC by tpaschidis

Convert gpio direct acces to leds interface

2022-07-01 13:01 UTC, dnietotwonav requested changes
Falta subir a 1.1.33?
**twonav_kernel_version**

2022-07-01 13:36 UTC, dnietotwonav approved these changes

2022-07-04 08:58 UTC, lluisdiaz commented on arch/arm/boot/dts/stonehenge-big-common.dtsi
> +		gprs_switch {
Ad far as I know, there's no reason for putting gprs gpio's under common stonehenge. 
About sd_switch, is ok if we want to sell "aventura" as "trail", but putting gpio's as outputs 
could increase power consumption unnecessarily

2022-07-04 08:59 UTC, lluisdiaz commented on arch/arm/boot/dts/stonehenge-big-common.dtsi
> +				MX6UL_PAD_ENET2_TX_DATA0__GPIO2_IO11    0x1b0b0 /* GPRS_STATUS (INPUT) */
same about gprs gpio's

2022-07-04 09:03 UTC, lluisdiaz requested changes
LGTM

2022-07-04 10:03 UTC, lluisdiaz approved these changes

2022-07-04 10:06 UTC, merged

2022-07-04 10:28 UTC, faragon2n reviewed
LGTM