Improve atmel touchscreen finger handling & bugfixing
twonav/linux-2.6-imx pull request #90
Opened 2021-12-15 14:09 UTC by tpaschidis

2021-12-15 14:52 UTC, dnietotwonav approved these changes

2021-12-16 10:38 UTC, lluisdiaz requested changes
si la intención del mutex es proteger las lecturas y escrituras de finger_key_id_array, falta proteger también la función `isFinger()` con el mutex

2021-12-16 10:42 UTC, lluisdiaz commented on drivers/input/touchscreen/atmel_mxt_ts.c
>  	for (i = 0; i < FINGER_ID_ARRAY_SIZE; i++) {
esto ya es pal jogo bonito, pero puedes hacer un `int find_first_key_index(int id)' ya que el for se repite 3 veces.

2021-12-20 13:01 UTC, lluisdiaz approved these changes

2021-12-20 13:13 UTC, merged